# configs/det_vit_fpn.yaml

task: detection
experiment_name: vit_fpn_det

# Dataset
train_annotations: ./data/coco/annotations/instances_train2017.json
train_images: ./data/coco/train2017
val_annotations: ./data/coco/annotations/instances_val2017.json
val_images: ./data/coco/val2017
num_classes: 91  # 90 + background for COCO

# Model
backbone: convnext_base.fb_in22k_ft_in1k  # or 'vit_base_patch16_224'
out_indices: [1, 2, 3]
fpn_out_channels: 256
pretrained_backbone: true

# Training
batch_size: 4
epochs: 12
lr: 0.005
momentum: 0.9
weight_decay: 0.0005
lr_step_size: 8
lr_gamma: 0.1
device: cuda

# Logging & Checkpoints
save_dir: ./experiments/det_vit_fpn/
eval_interval: 1
save_best: true
